### ISSUE TITLE
一些建议

### ISSUE THREAD

**Issue by Rratic** [Nictheboy/GHG#5]
你好像移除了颜色系统？

windows下也可以使用，但要先执行任意system指令，比如可以使用system("");

建议增加清屏功能，
```
#ifdef __linux
#define cls system("clear");
#endif
#ifdef _WIN32
#define cls system("cls")
#define fix_output system("chcp 65001");//以utf-8格式输出，读文本文件可能有用
#endif
```
错别字：

第二关

> 在上次让你练习telnet的那台主机上，存有一份wget.exe。你得在连接一次29.53.103.3，然后用scp指令把它复制过来。

在->再

**Comment by Nictheboy** [comment]
收到

**Comment by 026-Ink** [comment]
> 你好像移除了颜色系统？
> 
> windows下也可以使用，但要先执行任意system指令，比如可以使用system("");
> 
> 建议增加清屏功能，
> 
> ```
> #ifdef __linux
> #define cls system("clear");
> #endif
> #ifdef _WIN32
> #define cls system("cls")
> #define fix_output system("chcp 65001");//以utf-8格式输出，读文本文件可能有用
> #endif
> ```
> 
> 错别字：
> 
> 第二关
> 
> > 在上次让你练习telnet的那台主机上，存有一份wget.exe。你得在连接一次29.53.103.3，然后用scp指令把它复制过来。
> 
> 在->再

**Comment by NicholasYang21** [comment]
我们会使用windows API实现windows端的颜色系统。
感谢您的提议。

**Comment by NicholasYang21** [comment]
Bug已经修复完毕，我们将生成下一版并添加至Releases。
