### ISSUE TITLE
Add me into your GHG repository | 把我添加到你的GHG储存库里

### ISSUE THREAD

**Issue by AstralFlare-owo** [Nictheboy/GHG#6]
Can you add me into your GHG repository? I will help you something.
Or you can try this installer I made for you. (GHGInst140.exe in the GHGInst140.zip in the issue files)
============================Translate Line | 翻译线===============================
你可以把我添加到你的GHG储存库里吗？我可以在某些地方帮到你。
或者你可以试试我为你做的这个安装程序。（问题文件中的 GHGInst140.zip 中的 GHGInst140.exe）
[GHGInst140.zip](https://github.com/Nictheboy/GHG/files/6008544/GHGInst140.zip)

**Comment by Nictheboy** [comment]
搞定了
