### ISSUE TITLE
话说C++11支持多行字符串

### ISSUE THREAD

**Issue by Rratic** [Nictheboy/GHG#8]
[ref](https://zh.cppreference.com/w/cpp/language/string_literal)

u1s1，你准备以后支持批处理文件吗（在文件系统中弄个文件，用某个指令运行）

**Comment by Nictheboy** [comment]
以后过这个想法，但是我最近拿不到电脑

**Comment by Nictheboy** [comment]
我给你权限了，假如你有时间没准可以帮忙做了。用vs环境

**Comment by Nictheboy** [comment]
谢了

**Comment by Rratic** [comment]
有时间看看

**Comment by Rratic** [comment]
冗余代码太多了
我要写还是重写一个吧
